{
	"version": 1591563336,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/playeranmat-sheet0.png",
		"images/playeranmat-sheet1.png",
		"images/playeranmat-sheet2.png",
		"images/playersolid-sheet0.png",
		"images/shot-sheet0.png",
		"images/playerz-sheet0.png",
		"images/menubk.png",
		"images/btnstart-sheet0.png",
		"images/bkfxmenu-sheet0.png",
		"images/tiledbackground.png",
		"images/bk1-sheet0.png",
		"images/bk2-sheet0.png",
		"images/bk2-sheet1.png",
		"images/b4.png",
		"images/b6.png",
		"images/bk5.png",
		"images/bk4-sheet0.png",
		"images/homeblack-sheet0.png",
		"images/homeblack-sheet1.png",
		"images/gunbk-sheet0.png",
		"images/contorolarbk-sheet0.png",
		"images/contorolar-sheet0.png",
		"images/jumpbtn-sheet0.png",
		"images/chengshot-sheet0.png",
		"images/playerhelath-sheet0.png",
		"images/enamy1-sheet0.png",
		"images/enamy1fx.png",
		"images/shorenamy1-sheet0.png",
		"media/gun shot 1.ogg",
		"media/gun slide single 2.m4a",
		"media/gun slide single .ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}